[package]
name = "app_host"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "21.0.1"
wasmtime-wasi-http = "21.0.1"
wasmtime-wasi = "21.0.1"
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0"
wit-component = "0.209.1"